add

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,19 +19,20 @@ runs:
     #   run: echo "Root Dir: ${{ inputs.root_path }}"
     #   shell: bash
 
-    - name: Debug Action Path
-      run: |
-        echo "GitHub Action Path: ${{ github.action_path }}"
-        ls -R "${{ github.action_path }}" || echo "Directory not found!"
-      shell: bash
+    # - name: Debug Action Path
+    #   run: |
+    #     echo "GitHub Action Path: ${{ github.action_path }}"
+    #     ls -R "${{ github.action_path }}" || echo "Directory not found!"
+    #   shell: bash
 
-    - name: Debug Parent Action Directory
-      run: |
-        ls -R /home/runner/work/_actions/pengwinsurf/ApiCov || echo "Directory not found!"
-      shell: bash
+    # - name: Debug Parent Action Directory
+    #   run: |
+    #     ls -R /home/runner/work/_actions/pengwinsurf/ApiCov || echo "Directory not found!"
+    #   shell: bash
 
     - name: Run APICov
-      run: python3 /home/runner/work/_actions/pengwinsurf/ApiCov/src/apicov.py "${{ inputs.root_path }}" "${{ inputs.install_path }}"
+      run: ${GITHUB_ACTION_PATH}/dist/run.sh "${{ inputs.root_path }}" "${{ inputs.install_path }}"
+      # run: python3 /home/runner/work/_actions/pengwinsurf/ApiCov/src/apicov.py "${{ inputs.root_path }}" "${{ inputs.install_path }}"
       shell: bash
 
 
